name: Update FOREX Data in MacroDB Schema

on:
  push:
    branches: [ "feature/auto-update" ]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v6

      - name: Setup Python v6
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install Python & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute ERAPI Python Script
        env:
          DUMMY: ${{ secrets.DUMMY }}
        run: python main/erapi.py

      - name: Commit Logs to the New File
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || (git commit -a -m "üìù ERAPI Logs Updated" --allow-empty)

      - name: Push Changes to the Branch
        uses: ad-m/github-push-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/auto-update
